server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "https://payfinity-jgpd.vercel.app"
              - "https://payfinity-jgpd.vercel.app/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        # User Service
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**, /api/users/**

        # Transaction Service
        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/transactions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        # Reward Service
        - id: reward-service
          uri: ${REWARD_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/rewards/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        # Notification Service
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/notify/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"

        # Wallet Service
        - id: wallet-service
          uri: ${WALLET_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/v1/wallets/**

      httpclient:
        max-initial-line-length: 4096
        max-header-size: 8192

      filters:
        - name: RequestSize
          args:
            maxSize: 1MB

jwt:
  secret: my-super-secret-key-that-you-never-share