server:
  port: 8080

spring:
  application:
    name: transaction-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: transaction-events

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-polished-recipe-ah6no5s9-pooler.c-3.us-east-1.aws.neon.tech/paypal_transaction?sslmode=require&channel_binding=require}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_h0uKZJPzE7Hx}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect